name:                evdev
version:             0.1.0.0
github:              "ocecaco/evdev"
license:             BSD3
author:              "Daniël Louwrink"
maintainer:          "daniel.louwrink@gmail.com"
copyright:           "2018 Daniël Louwrink"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ocecaco/evdev#readme>

dependencies:
- base >= 4.7 && < 5
- bindings-DSL
- unix

library:
  source-dirs: src
  default-extensions: ForeignFunctionInterface  # TODO: maybe put at top of files instead
  pkg-config-dependencies: libevdev

executables:
  evdev-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - evdev

tests:
  evdev-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - evdev
